// Copyright 2021-2024 FRC 6328
// http://github.com/Mechanical-Advantage
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// version 3 as published by the Free Software Foundation or
// available in the root directory of this project.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

package frc.robot.subsystems.vision;

import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.subsystems.drive.Drive;
import frc.robot.subsystems.vision.VisionConstants;
import org.littletonrobotics.junction.AutoLogOutput;
import org.littletonrobotics.junction.Logger;

/**
 * Vision subsystem for processing Limelight camera data with MegaTag 2.
 * 
 * <p>This subsystem:
 * <ul>
 *   <li>Updates robot orientation to Limelight every cycle (required for MegaTag 2)</li>
 *   <li>Processes pose estimates from multiple cameras</li>
 *   <li>Calculates dynamic standard deviations based on tag count and distance</li>
 *   <li>Adds vision measurements to the drive subsystem's pose estimator</li>
 *   <li>Trusts gyro for rotation (rotation std dev = infinity)</li>
 * </ul>
 */
public class Vision extends SubsystemBase {
  private final VisionIO leftCameraIO;
  private final VisionIO rightCameraIO;
  // Note: VisionIOInputsAutoLogged is auto-generated by AdvantageKit annotation processor
  // The class will be available after compilation
  private final VisionIOInputsAutoLogged leftInputs = new VisionIOInputsAutoLogged();
  private final VisionIOInputsAutoLogged rightInputs = new VisionIOInputsAutoLogged();
  
  private final Drive drive;
  
  /** Last gyro yaw for orientation updates */
  private double lastYaw = 0.0;
  
  /** Last gyro angular velocity for orientation updates */
  private double lastYawVelocity = 0.0;

  /** Last robot state for throttle management */
  private boolean lastEnabledState = false;

  /**
   * Creates a new Vision subsystem.
   *
   * @param leftCameraIO IO implementation for the left camera
   * @param rightCameraIO IO implementation for the right camera
   * @param drive Drive subsystem to get gyro data and add vision measurements
   */
  public Vision(VisionIO leftCameraIO, VisionIO rightCameraIO, Drive drive) {
    this.leftCameraIO = leftCameraIO;
    this.rightCameraIO = rightCameraIO;
    this.drive = drive;

    // Configure IMU mode for MegaTag 2 (use internal IMU for best performance)
    leftCameraIO.setIMUMode(VisionConstants.IMU_MODE);
    rightCameraIO.setIMUMode(VisionConstants.IMU_MODE);
  }

  @Override
  public void periodic() {
    // Thermal management: Set throttle based on robot state
    boolean isEnabled = DriverStation.isEnabled();
    if (isEnabled != lastEnabledState) {
      // State changed, update throttle
      if (isEnabled) {
        // Robot enabled - full speed (throttle = 0)
        leftCameraIO.setThrottle(VisionConstants.THROTTLE_ENABLED);
        rightCameraIO.setThrottle(VisionConstants.THROTTLE_ENABLED);
        Logger.recordOutput("Vision/ThrottleMode", "Enabled");
      } else {
        // Robot disabled - throttle to reduce heat (throttle = 150)
        leftCameraIO.setThrottle(VisionConstants.THROTTLE_DISABLED);
        rightCameraIO.setThrottle(VisionConstants.THROTTLE_DISABLED);
        Logger.recordOutput("Vision/ThrottleMode", "Disabled");
      }
      lastEnabledState = isEnabled;
    }

    // Get current gyro data from drive subsystem
    Rotation2d currentYaw = drive.getRotation();
    double yawRadians = currentYaw.getDegrees();
    
    // Calculate angular velocity (simple difference, could be improved with filtering)
    double yawVelocity = (yawRadians - lastYaw) / 0.02; // 20ms loop period
    double yawVelocityDegPerSec = Math.abs(yawVelocity);
    lastYaw = yawRadians;
    lastYawVelocity = yawVelocity;

    // CRITICAL: Update robot orientation to Limelight every cycle for MegaTag 2
    // Only update when enabled (MegaTag 2 not needed when disabled)
    if (isEnabled) {
leftCameraIO.setRobotOrientation(currentYaw.getDegrees(), Math.toDegrees(yawVelocity));
  rightCameraIO.setRobotOrientation(currentYaw.getDegrees(), Math.toDegrees(yawVelocity));    }

    // Update inputs from cameras
    leftCameraIO.updateInputs(leftInputs);
    rightCameraIO.updateInputs(rightInputs);

    // Process inputs for logging
    Logger.processInputs("Vision/Left", leftInputs);
    Logger.processInputs("Vision/Right", rightInputs);

    // Process vision measurements from both cameras
    processVisionMeasurement(leftInputs, "Left");
    processVisionMeasurement(rightInputs, "Right");

    // Log outputs
    Logger.recordOutput("Vision/GyroYawRad", yawRadians);
    Logger.recordOutput("Vision/GyroYawVelocityRadPerSec", yawVelocity);
  }

  /**
   * Processes a vision measurement and adds it to the pose estimator with dynamic standard deviations.
   *
   * @param inputs Vision inputs from a camera (VisionIOInputsAutoLogged)
   * @param cameraName Name of the camera for logging
   */
  private void processVisionMeasurement(VisionIOInputsAutoLogged inputs, String cameraName) {
    // Reject if no pose estimate
    if (!inputs.hasPose || inputs.visionPose == null) {
      return;
    }

    // Reject if no tags detected (MegaTag 2 requirement)
    if (inputs.tagCount == 0) {
      Logger.recordOutput("Vision/" + cameraName + "/MeasurementRejected", "NoTags");
      return;
    }

    // Check if measurement is too old
    double measurementAge = Timer.getFPGATimestamp() - inputs.poseTimestamp;
    if (measurementAge > VisionConstants.MAX_MEASUREMENT_AGE) {
      Logger.recordOutput("Vision/" + cameraName + "/MeasurementRejected", "TooOld");
      return;
    }

    // Filter out updates when angular velocity is too high (Limelight recommendation)
    // High angular velocity causes blur and inaccurate pose estimates
    double yawVelocityDegPerSec = Math.abs(Math.toDegrees(lastYawVelocity));
    if (yawVelocityDegPerSec > VisionConstants.MAX_ACCEPTABLE_ANGULAR_VELOCITY_DEG_PER_SEC) {
      Logger.recordOutput("Vision/" + cameraName + "/MeasurementRejected", "AngularVelocityTooHigh");
      Logger.recordOutput("Vision/" + cameraName + "/AngularVelocityDegPerSec", yawVelocityDegPerSec);
      return;
    }

    // Calculate dynamic standard deviations based on tag count and distance
    double stdDevX, stdDevY, stdDevTheta;

    if (inputs.tagCount >= VisionConstants.MIN_TAGS_FOR_HIGH_CONFIDENCE) {
      // Multiple tags detected - trust vision highly
      stdDevX = VisionConstants.MULTI_TAG_STD_DEV;
      stdDevY = VisionConstants.MULTI_TAG_STD_DEV;
      Logger.recordOutput("Vision/" + cameraName + "/Confidence", "High");
    } else if (inputs.tagCount == 1) {
      // Single tag - trust based on distance
      double distance = inputs.closestTagDistance;
      
      if (distance > VisionConstants.MAX_SINGLE_TAG_DISTANCE) {
        // Far away - trust less
        stdDevX = VisionConstants.FAR_SINGLE_TAG_STD_DEV;
        stdDevY = VisionConstants.FAR_SINGLE_TAG_STD_DEV;
        Logger.recordOutput("Vision/" + cameraName + "/Confidence", "Low");
      } else {
        // Close - trust more
        // Interpolate between close and far based on distance
        double ratio = distance / VisionConstants.MAX_SINGLE_TAG_DISTANCE;
        stdDevX = VisionConstants.CLOSE_SINGLE_TAG_STD_DEV
            + (VisionConstants.FAR_SINGLE_TAG_STD_DEV - VisionConstants.CLOSE_SINGLE_TAG_STD_DEV) * ratio;
        stdDevY = stdDevX;
        Logger.recordOutput("Vision/" + cameraName + "/Confidence", "Medium");
      }
    } else {
      // No tags - don't trust this measurement
      Logger.recordOutput("Vision/" + cameraName + "/MeasurementRejected", "NoTags");
      return;
    }

    // Trust gyro for rotation - set rotation std dev to infinity
    stdDevTheta = VisionConstants.ROTATION_STD_DEV;

    // Log standard deviations
    Logger.recordOutput("Vision/" + cameraName + "/StdDevX", stdDevX);
    Logger.recordOutput("Vision/" + cameraName + "/StdDevY", stdDevY);
    Logger.recordOutput("Vision/" + cameraName + "/StdDevTheta", stdDevTheta);
    Logger.recordOutput("Vision/" + cameraName + "/TagCount", inputs.tagCount);
    Logger.recordOutput("Vision/" + cameraName + "/ClosestTagDistance", inputs.closestTagDistance);

    // Add vision measurement to pose estimator with calculated standard deviations
    // Note: SwerveDrivePoseEstimator.addVisionMeasurement() takes a Pose2d and timestamp
    // Standard deviations are set via the constructor or can be set per measurement
    // We'll use the method that accepts standard deviations if available
    addVisionMeasurementWithStdDevs(
        inputs.visionPose,
        inputs.poseTimestamp,
        stdDevX,
        stdDevY,
        stdDevTheta);
  }

  /**
   * Adds a vision measurement to the pose estimator with specified standard deviations.
   *
   * @param pose Vision pose estimate
   * @param timestamp Timestamp of the measurement
   * @param stdDevX Standard deviation for X translation
   * @param stdDevY Standard deviation for Y translation
   * @param stdDevTheta Standard deviation for rotation
   */
  private void addVisionMeasurementWithStdDevs(
      Pose2d pose, double timestamp, double stdDevX, double stdDevY, double stdDevTheta) {
    // Add vision measurement with dynamic standard deviations
    drive.addVisionMeasurement(pose, timestamp, VecBuilder.fill(stdDevX, stdDevY, stdDevTheta));    
    // Log that we're using dynamic standard deviations
    Logger.recordOutput("Vision/MeasurementAdded", true);
    Logger.recordOutput("Vision/LastStdDevX", stdDevX);
    Logger.recordOutput("Vision/LastStdDevY", stdDevY);
    Logger.recordOutput("Vision/LastStdDevTheta", stdDevTheta);
  }

  /**
   * Gets whether the left camera has a valid pose estimate.
   *
   * @return True if left camera has valid pose
   */
  @AutoLogOutput(key = "Vision/Left/HasValidPose")
  public boolean leftHasValidPose() {
    return leftInputs.hasPose;
  }

  /**
   * Gets whether the right camera has a valid pose estimate.
   *
   * @return True if right camera has valid pose
   */
  @AutoLogOutput(key = "Vision/Right/HasValidPose")
  public boolean rightHasValidPose() {
    return rightInputs.hasPose;
  }

  /**
   * Gets the total number of tags detected across all cameras.
   *
   * @return Total tag count
   */
  @AutoLogOutput(key = "Vision/TotalTagCount")
  public int getTotalTagCount() {
    return leftInputs.tagCount + rightInputs.tagCount;
  }

  /**
   * Gets the left camera's latest pose estimate.
   *
   * @return Pose estimate, or null if not available
   */
  public Pose2d getLeftPose() {
    return leftInputs.hasPose ? leftInputs.visionPose : null;
  }

  /**
   * Gets the right camera's latest pose estimate.
   *
   * @return Pose estimate, or null if not available
   */
  public Pose2d getRightPose() {
    return rightInputs.hasPose ? rightInputs.visionPose : null;
  }
}

